version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: fds-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fds_users
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  zookeeper:
    image: bitnami/zookeeper:3.9
    container_name: fds-zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    healthcheck:
      test: ["CMD", "bash", "-c", "echo stat | nc localhost 2181 | grep Mode"]
      interval: 10s
      timeout: 5s
      retries: 10

  kafka:
    image: bitnami/kafka:3.7
    container_name: fds-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD", "bash", "-c", "kafka-topics.sh --bootstrap-server localhost:9092 --list | cat"]
      interval: 15s
      timeout: 10s
      retries: 15

  eureka-server:
    build: ./eureka-server
    image: fds/eureka-server:local
    container_name: fds-eureka
    depends_on:
      - mysql
    ports:
      - "8761:8761"
    environment:
      EUREKA_SERVER_PORT: 8761
    healthcheck:
      test: ["CMD", "bash", "-lc", "wget -qO- http://localhost:8761 | cat"]
      interval: 15s
      timeout: 10s
      retries: 20

  api-gateway:
    build: ./api-gateway
    image: fds/api-gateway:local
    container_name: fds-gateway
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
    environment:
      GATEWAY_PORT: 8080
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      JWT_SECRET: supersecretjwtkeychangeme

  user-service:
    build: ./user-service
    image: fds/user-service:local
    container_name: fds-user
    depends_on:
      - mysql
      - eureka-server
      - kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: fds_users
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP: kafka:9092
      JWT_SECRET: supersecretjwtkeychangeme

  restaurant-service:
    build: ./restaurant-service
    image: fds/restaurant-service:local
    container_name: fds-restaurant
    depends_on:
      - mysql
      - eureka-server
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: fds_restaurants
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/

  order-service:
    build: ./order-service
    image: fds/order-service:local
    container_name: fds-order
    depends_on:
      - mysql
      - eureka-server
      - kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: fds_orders
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP: kafka:9092

  payment-service:
    build: ./payment-service
    image: fds/payment-service:local
    container_name: fds-payment
    depends_on:
      - mysql
      - eureka-server
      - kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: fds_payments
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP: kafka:9092

  delivery-service:
    build: ./delivery-service
    image: fds/delivery-service:local
    container_name: fds-delivery
    depends_on:
      - mysql
      - eureka-server
      - kafka
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: fds_delivery
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP: kafka:9092

  notification-service:
    build: ./notification-service
    image: fds/notification-service:local
    container_name: fds-notification
    depends_on:
      - eureka-server
      - kafka
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP: kafka:9092

volumes:
  mysql_data:

networks:
  default:
    name: fds-net
    driver: bridge

