server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**, /users/**
        - id: restaurant-service
          uri: lb://restaurant-service
          predicates:
            - Path=/restaurants/**, /menus/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**
        - id: delivery-service
          uri: lb://delivery-service
          predicates:
            - Path=/deliveries/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}

security:
  jwt:
    secret: ${JWT_SECRET:supersecretjwtkeychangeme}

management:
  endpoints:
    web:
      exposure:
        include: "*"

