name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build services with Maven
        run: |
          mvn -q -e -DskipTests -f /workspace/pom.xml package || mvn -q -e -DskipTests package
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci || npm install
          npm run build

